### ISSUE TITLE
dev dependencies: optional-dependencies → dependency-groups

### ISSUE THREAD

**Issue by osoken** [adrai-org/adr-ai-tools-py#3]
## Overview

Based on PEP 735, we propose migrating development dependencies from `project.optional-dependencies`'s `dev` group to `dependency-groups`.

## Background

Currently, development dependencies are managed in the `dev` group of `project.optional-dependencies` in `pyproject.toml`. However, migration to `dependency-groups` is recommended for the following reasons:

- `optional-dependencies` are published as package metadata, making development dependencies part of the public interface
- `optional-dependencies` always require installing the current package and its dependencies
- New package managers (e.g., `uv`) prioritize support for `dependency-groups`

## Changes

We will modify `pyproject.toml` as follows:

```toml
# Before
[project.optional-dependencies]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.11.10",
]

# After
[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.11.10",
]
```

## Impact

- Changes the way development dependencies are installed
- Improves compatibility with new package managers (like `uv`)
- Removes development dependencies from package metadata

## References

- [PEP 735 – Dependency Groups in pyproject.toml](https://peps.python.org/pep-0735/)
